<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <StartupObject>MikoInstaller.Program</StartupObject>
    <UseWPF>true</UseWPF>
    <LangVersion>latest</LangVersion>
    <ApplicationIcon>assets\icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="assets\banner.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.IO.Compression" Version="4.3.0" />
    <PackageReference Include="System.IO.Compression.ZipFile" Version="4.3.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Windows.Forms" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="assets\app.zip" />
  </ItemGroup>

</Project>